-- 自动生成的 UPDATE 语句,补充 additive_knowledge.safety_desc 与 disease_contraindication
-- 共 266 条,源自 db/_fill_data.py
SET NAMES utf8mb4;
USE health_food;

UPDATE additive_knowledge SET safety_desc='用于鲜水产护色防黑变,可抑制酚酶活性。JECFA设ADI为0-0.5 mg/kg体重,合规剂量下风险低。结构属苯酚类,残留过高可能刺激消化道。', disease_contraindication='苯酚类过敏者慎用' WHERE id=83;
UPDATE additive_knowledge SET safety_desc='5''-肌苷酸二钠和5''-鸟苷酸二钠的等量混合物,广泛用于增鲜。在体内代谢为尿酸经肾排出,JECFA认为常规用量下安全。', disease_contraindication='痛风、高尿酸血症患者慎用' WHERE id=21;
UPDATE additive_knowledge SET safety_desc='核糖核酸水解得到的核苷酸增味剂,与谷氨酸钠协同显著增强鲜味。在体内代谢为尿酸,常规用量下安全。', disease_contraindication='痛风、高尿酸血症、严重肾病者慎用' WHERE id=81;
UPDATE additive_knowledge SET safety_desc='核苷酸类增味剂,与谷氨酸钠混合可显著增强鲜味。代谢途径与肌苷酸相同,产物为尿酸。常规用量下安全。', disease_contraindication='痛风、高尿酸血症患者慎用' WHERE id=157;
UPDATE additive_knowledge SET safety_desc='多元醇甜味剂,甜度约为蔗糖50%-70%,血糖反应低。人体吸收率低,大部分经肠道排出,过量可引起渗透性腹泻。JECFA认定ADI''无需规定''。', disease_contraindication='肠易激综合征、慢性腹泻者大量摄入慎用' WHERE id=53;
UPDATE additive_knowledge SET safety_desc='维生素C的立体异构体,无维生素C营养活性但抗氧化能力相近,常用于肉制品护色和饮料抗氧化。JECFA认定ADI''无需规定'',合规剂量内安全。', disease_contraindication='无明显禁忌人群' WHERE id=265;
UPDATE additive_knowledge SET safety_desc='水果中天然存在的有机酸,人体三羧酸循环中间产物,可被完全代谢为二氧化碳和水。JECFA认定ADI''无需规定'',过量可能刺激胃黏膜。', disease_contraindication='胃溃疡、胃酸过多者慎用' WHERE id=169;
UPDATE additive_knowledge SET safety_desc='DL-苹果酸的钠盐形式,作酸度调节剂和缓冲剂。在体内解离为苹果酸根和钠离子,代谢途径正常。JECFA认定ADI''无需规定''。', disease_contraindication='高血压、限钠饮食者慎用' WHERE id=166;
UPDATE additive_knowledge SET safety_desc='含硫氨基酸的盐酸盐,用于改善面团延展性。属人体非必需氨基酸的衍生物,常规用量下安全。JECFA未设ADI上限。', disease_contraindication='胱氨酸尿症患者慎用' WHERE id=8;
UPDATE additive_knowledge SET safety_desc='人体非必需氨基酸,广泛存在于蛋白质中,可被正常代谢为葡萄糖和能量。JECFA认定ADI''无需规定'',安全性极高。', disease_contraindication='无明显禁忌人群' WHERE id=14;
UPDATE additive_knowledge SET safety_desc='葡萄等水果中天然存在的有机酸,常用于配制酒和糖果调酸。JECFA设ADI为0-30 mg/kg体重,合规剂量内安全,过量可能引起腹泻。', disease_contraindication='胃溃疡、慢性腹泻者慎用' WHERE id=94;
UPDATE additive_knowledge SET safety_desc='苹果等水果中天然存在的L型异构体,人体三羧酸循环中间产物,代谢途径明确。JECFA认定ADI''无需规定''。', disease_contraindication='胃溃疡、胃酸过多者慎用' WHERE id=167;
UPDATE additive_knowledge SET safety_desc='L-苹果酸的钠盐形式,作酸度调节剂和缓冲剂。代谢途径与L-苹果酸相同,JECFA认定ADI''无需规定''。', disease_contraindication='高血压、限钠饮食者慎用' WHERE id=168;
UPDATE additive_knowledge SET safety_desc='由6个葡萄糖单元组成的环状寡糖,属水溶性膳食纤维,在结肠被微生物发酵分解。JECFA认定ADI''无需规定'',过量可能引起腹胀。', disease_contraindication='肠易激综合征者大量摄入易腹胀' WHERE id=78;
UPDATE additive_knowledge SET safety_desc='类胡萝卜素衍生物,在体内可部分转化为维生素A。JECFA设ADI为0-5 mg/kg体重,合规剂量下风险低,长期超量可能皮肤黄染。', disease_contraindication='维生素A过量者、孕妇高剂量摄入慎用' WHERE id=2;
UPDATE additive_knowledge SET safety_desc='维生素A原,广泛存在于胡萝卜、南瓜等食物中,可在体内按需转化为维生素A。JECFA设ADI为0-5 mg/kg体重。重度吸烟者大剂量补充可能增加肺癌风险。', disease_contraindication='重度吸烟者长期大剂量补充慎用' WHERE id=71;
UPDATE additive_knowledge SET safety_desc='由7个葡萄糖单元组成的环状寡糖,可包合脂溶性物质。JECFA设ADI为0-5 mg/kg体重,合规剂量下安全,过量可能引起腹胀。', disease_contraindication='肠易激综合征者慎用' WHERE id=80;
UPDATE additive_knowledge SET safety_desc='由8个葡萄糖单元组成的环状寡糖,水溶性最佳,可被淀粉酶部分水解。JECFA认定ADI''无需规定'',安全性高。', disease_contraindication='无明显禁忌人群' WHERE id=79;
UPDATE additive_knowledge SET safety_desc='放线菌发酵产生的天然抗菌肽,在体内可水解为赖氨酸被吸收。JECFA认为常规用量下安全,日本、美国已批准多年使用。', disease_contraindication='无明显禁忌人群' WHERE id=102;
UPDATE additive_knowledge SET safety_desc='ε-聚赖氨酸的盐酸盐形式,水溶性更佳。属生物来源,可代谢为赖氨酸。常规用量下安全性高。', disease_contraindication='无明显禁忌人群' WHERE id=103;
UPDATE additive_knowledge SET safety_desc='阿拉伯胶树渗出液,属水溶性膳食纤维,人体不消化吸收。JECFA认定ADI''无需规定'',安全性极高,过量可能引起腹胀。', disease_contraindication='无明显禁忌人群,过敏体质慎用' WHERE id=1;
UPDATE additive_knowledge SET safety_desc='二肽类高甜度甜味剂,甜度约为蔗糖2000倍,在体内水解为天冬氨酸和小肽。JECFA设ADI为0-1 mg/kg体重,不含游离苯丙氨酸。', disease_contraindication='孕妇、儿童慎用' WHERE id=222;
UPDATE additive_knowledge SET safety_desc='阿斯巴甜衍生甜味剂,甜度约为蔗糖20000倍,极低剂量即可达到甜度需求,代谢生成的苯丙氨酸量远低于膳食水平。JECFA设ADI为0-5 mg/kg体重。', disease_contraindication='苯丙酮尿症患者大量摄入慎用' WHERE id=3;
UPDATE additive_knowledge SET safety_desc='最简单的氨基酸,人体可自身合成,广泛存在于蛋白质中。代谢途径明确,JECFA认定ADI''无需规定'',安全性极高。', disease_contraindication='无明显禁忌人群' WHERE id=4;
UPDATE additive_knowledge SET safety_desc='主要用于巧克力降低粘度、改善加工流变性。在体内可水解为甘油、脂肪酸和磷酸盐。JECFA设ADI为0-30 mg/kg体重。', disease_contraindication='高磷血症、肾功能不全者慎用' WHERE id=5;
UPDATE additive_knowledge SET safety_desc='巴西棕榈树叶提取的天然蜡质,主要成分为脂肪酸蜡酯,人体不消化吸收,直接经肠道排出。JECFA设ADI为0-7 mg/kg体重。', disease_contraindication='无明显禁忌人群' WHERE id=6;
UPDATE additive_knowledge SET safety_desc='高度精炼矿物油,化学性质稳定,人体几乎不吸收,仅用于鲜蛋和部分糖果包衣。JECFA对食品级白油设ADI为0-20 mg/kg体重,长期大量摄入可能干扰脂溶性维生素吸收。', disease_contraindication='婴幼儿、孕妇、慢性肠道疾病患者慎用' WHERE id=7;
UPDATE additive_knowledge SET safety_desc='多种植物胶的主要骨架成分,属水溶性膳食纤维,人体不消化吸收。安全性较高,过量摄入可能引起腹胀。', disease_contraindication='无明显禁忌人群' WHERE id=9;
UPDATE additive_knowledge SET safety_desc='从特定深海鱼或微生物中获取的特殊蛋白,可抑制冷冻饮品中冰晶生长。属蛋白质,可被消化吸收,常规用量下安全。', disease_contraindication='鱼类蛋白过敏者慎用' WHERE id=13;
UPDATE additive_knowledge SET safety_desc='工业法生产的高纯度乙酸,化学结构与醋酸相同,在体内进入正常脂肪酸代谢途径。JECFA认定ADI''无需规定''。', disease_contraindication='胃溃疡、胃酸过多者慎用' WHERE id=12;
UPDATE additive_knowledge SET safety_desc='食醋的主要呈酸成分,人体可代谢为二氧化碳和水。JECFA认定ADI''无需规定'',过量摄入或高浓度接触可能刺激胃黏膜。', disease_contraindication='胃溃疡、胃酸过多者慎用' WHERE id=11;
UPDATE additive_knowledge SET safety_desc='化学合成多元醇,在体内可氧化代谢为乳酸或与葡萄糖醛酸结合排出。JECFA设ADI为0-25 mg/kg体重,婴幼儿代谢能力较弱。', disease_contraindication='婴幼儿、孕妇、严重肝肾功能不全者慎用' WHERE id=15;
UPDATE additive_knowledge SET safety_desc='丙二醇与脂肪酸酯化产物,在体内水解为丙二醇和脂肪酸。JECFA设ADI为0-25 mg/kg体重,合规剂量下安全。', disease_contraindication='婴幼儿大量摄入慎用' WHERE id=16;
UPDATE additive_knowledge SET safety_desc='短链脂肪酸,广泛存在于乳制品中,人体可正常代谢供能,常用于面包防霉。JECFA认定ADI''无需规定'',安全性高。', disease_contraindication='丙酸代谢障碍患者(罕见)禁用' WHERE id=17;
UPDATE additive_knowledge SET safety_desc='茶叶提取物,主要成分为儿茶素类多酚,具强抗氧化活性。常规剂量下对人体有益,过量可能干扰铁吸收或加重肝脏负担。', disease_contraindication='缺铁性贫血、肝功能不全者大量摄入慎用' WHERE id=18;
UPDATE additive_knowledge SET safety_desc='茶多酚经棕榈酸酯化得到的脂溶性衍生物,用于油脂抗氧化。在消化道水解后释放茶多酚和棕榈酸,代谢路径明确。', disease_contraindication='无明显禁忌人群' WHERE id=19;
UPDATE additive_knowledge SET safety_desc='红茶发酵中茶多酚的氧化产物,具显著抗氧化和抗菌活性,属食物本身成分,合规剂量下安全。', disease_contraindication='无明显禁忌人群' WHERE id=20;
UPDATE additive_knowledge SET safety_desc='含碘的合成红色素,JECFA设ADI为0-0.1 mg/kg体重。摄入后大部分以原形随粪便排出,少量代谢释放碘,长期大量摄入可能影响甲状腺功能。', disease_contraindication='甲状腺功能异常、碘过敏、儿童多动症者慎用' WHERE id=22;
UPDATE additive_knowledge SET safety_desc='四碳糖醇,血糖反应几乎为零,90%经尿排出不参与代谢。JECFA认定ADI''无需规定'',肠道耐受性优于其他糖醇,过量可能轻度腹泻。', disease_contraindication='肠易激综合征者大量摄入易腹泻' WHERE id=23;
UPDATE additive_knowledge SET safety_desc='印度梧桐树渗出液,水溶性膳食纤维,人体不消化吸收。JECFA认定ADI''无需规定''。', disease_contraindication='过敏体质者慎用' WHERE id=24;
UPDATE additive_knowledge SET safety_desc='刺云实种子胚乳提取的半乳甘露聚糖,水溶性膳食纤维。JECFA认定ADI''无需规定'',过量可能引起腹胀。', disease_contraindication='无明显禁忌人群' WHERE id=25;
UPDATE additive_knowledge SET safety_desc='玉米、木薯等淀粉经醋酸酯化的变性淀粉,改善冻融稳定性。在肠道部分水解为葡萄糖和乙酸,JECFA认定ADI''无需规定''。', disease_contraindication='无明显禁忌人群' WHERE id=26;
UPDATE additive_knowledge SET safety_desc='印度达瓦树渗出液,水溶性膳食纤维,仅限用于特殊膳食用食品。JECFA设ADI暂定参考值。', disease_contraindication='过敏体质者慎用' WHERE id=27;
UPDATE additive_knowledge SET safety_desc='由甘油与脂肪酸酯化得到,可被消化道脂肪酶水解为甘油和脂肪酸,代谢路径与天然脂肪一致。JECFA认定ADI''无需规定''。', disease_contraindication='无明显禁忌人群' WHERE id=28;
UPDATE additive_knowledge SET safety_desc='中链脂肪酸的甘油单酯,具广谱抑菌性。在体内水解为甘油和辛酸,辛酸经β-氧化代谢供能。常规用量下安全。', disease_contraindication='无明显禁忌人群' WHERE id=29;
UPDATE additive_knowledge SET safety_desc='大气主要成分,化学性质稳定,在饮料中作惰性气体或冷冻介质。无毒,合规使用下安全。', disease_contraindication='无明显禁忌人群' WHERE id=30;
UPDATE additive_knowledge SET safety_desc='经磷酸单酯化的变性淀粉,改善淀粉糊稳定性。在肠道水解释放葡萄糖和微量磷酸。JECFA认定ADI''无需规定''。', disease_contraindication='严重肾功能不全者大量摄入慎用' WHERE id=31;
UPDATE additive_knowledge SET safety_desc='合成蓝色素,JECFA设ADI为0-5 mg/kg体重。摄入后大部分以原形随粪便排出,少数敏感人群可能出现皮肤过敏或胃肠不适。', disease_contraindication='过敏体质、儿童多动症者慎用' WHERE id=32;
UPDATE additive_knowledge SET safety_desc='即尼泊金酯类防腐剂,在体内水解为对羟基苯甲酸经尿排出。JECFA设ADI为0-10 mg/kg体重,部分研究提示可能存在微弱内分泌干扰活性。', disease_contraindication='内分泌敏感人群、孕妇、婴幼儿慎用' WHERE id=34;
UPDATE additive_knowledge SET safety_desc='用于冷灌装饮料的瞬时灭菌剂,在饮料中迅速水解为甲醇和二氧化碳,残留极低。JECFA设ADI暂定值,需关注甲醇释放量。', disease_contraindication='婴幼儿、孕妇、甲醇代谢异常者慎用' WHERE id=37;
UPDATE additive_knowledge SET safety_desc='即食品级硅胶,化学性质稳定,人体不吸收,直接经肠道排出。JECFA认定ADI''无需规定'',安全性高。', disease_contraindication='无明显禁忌人群' WHERE id=38;
UPDATE additive_knowledge SET safety_desc='常见漂白剂和防腐剂,在食品中以亚硫酸盐形式残留,可释放二氧化硫。摄入后大部分经肝脏代谢为硫酸盐随尿排出,合规剂量下风险较低。残留过高可能引发头痛、恶心,敏感人群可诱发哮喘发作。', disease_contraindication='哮喘、亚硫酸盐过敏、肝肾功能不全' WHERE id=39;
UPDATE additive_knowledge SET safety_desc='白色无机颜料,人体几乎不吸收。JECFA曾设ADI''无需规定'',2021年欧盟EFSA因纳米级颗粒遗传毒性证据不足以排除而禁用,我国仍允许在GB 2760规定范围内使用。', disease_contraindication='婴幼儿、孕妇大量摄入慎用' WHERE id=40;
UPDATE additive_knowledge SET safety_desc='大气成分之一,广泛用于碳酸饮料和保鲜包装,人体可正常代谢。安全性极高。', disease_contraindication='严重胃食管反流者过量饮用碳酸饮料慎用' WHERE id=41;
UPDATE additive_knowledge SET safety_desc='番茄果实提取的天然红色素,主要成分为番茄红素及其他类胡萝卜素,具抗氧化活性。', disease_contraindication='无明显禁忌人群' WHERE id=42;
UPDATE additive_knowledge SET safety_desc='番茄等红色蔬果中的天然类胡萝卜素,有强抗氧化活性。JECFA设ADI为0-0.5 mg/kg体重,长期大量摄入可能皮肤微黄。', disease_contraindication='无明显禁忌人群' WHERE id=43;
UPDATE additive_knowledge SET safety_desc='蜜蜂分泌的天然蜡,主要成分为长链脂肪酸酯,人体不消化吸收。JECFA认定ADI''无需规定''。', disease_contraindication='蜂产品过敏者禁用' WHERE id=44;
UPDATE additive_knowledge SET safety_desc='三羧酸循环中间产物,人体可完全代谢。JECFA设ADI为0-6 mg/kg体重,合规剂量下安全。', disease_contraindication='胃溃疡者慎用' WHERE id=45;
UPDATE additive_knowledge SET safety_desc='富马酸的钠盐,在体内解离为富马酸根和钠离子,代谢路径与富马酸相同。', disease_contraindication='高血压、限钠饮食者慎用' WHERE id=46;
UPDATE additive_knowledge SET safety_desc='大豆磷脂经化学或酶法改性以提高乳化性能,主要成分仍为磷脂酰胆碱等,可被人体正常消化吸收。', disease_contraindication='大豆过敏者慎用' WHERE id=47;
UPDATE additive_knowledge SET safety_desc='甘草根提取物,含黄酮类化合物,具抗氧化活性。常规用量下安全。长期大量摄入甘草甜素可能引起血压升高和低血钾。', disease_contraindication='高血压、低钾血症、心衰、孕妇慎用' WHERE id=48;
UPDATE additive_knowledge SET safety_desc='甘草根中提取的天然甜味剂,甜度约为蔗糖50-100倍。长期大量摄入可引起假性醛固酮增多症,导致高血压、低血钾。JECFA设ADI暂定值。', disease_contraindication='高血压、低钾血症、心衰、肾病、孕妇慎用' WHERE id=49;
UPDATE additive_knowledge SET safety_desc='三羧酸循环底物,人体可完全代谢供能。JECFA认定ADI''无需规定'',安全性极高,过量可能引起渗透性腹泻。', disease_contraindication='无明显禁忌人群' WHERE id=50;
UPDATE additive_knowledge SET safety_desc='柑橘类果皮提取的天然黄色素,主要成分为类胡萝卜素,合规用量下风险低。', disease_contraindication='无明显禁忌人群' WHERE id=51;
UPDATE additive_knowledge SET safety_desc='高粱壳提取的天然红色素,属花色苷类,合规用量下风险低。', disease_contraindication='无明显禁忌人群' WHERE id=52;
UPDATE additive_knowledge SET safety_desc='强氧化剂,仅限作为食用淀粉处理剂在严格剂量下使用,残留极低。直接接触高浓度溶液有强腐蚀性,正常残留水平下安全。', disease_contraindication='不涉及成品消费者直接接触,无明显禁忌人群' WHERE id=54;
UPDATE additive_knowledge SET safety_desc='微生物发酵生产的酶制剂,可催化蛋白质交联,改善豆制品和肉制品质构。在加工和消化过程中失活,本身被消化为氨基酸,安全性高。', disease_contraindication='无明显禁忌人群' WHERE id=56;
UPDATE additive_knowledge SET safety_desc='瓜尔豆胚乳提取的水溶性膳食纤维,人体不消化吸收。JECFA认定ADI''无需规定'',可降低餐后血糖反应,过量可能引起腹胀。', disease_contraindication='肠梗阻、严重吞咽困难者慎用' WHERE id=57;
UPDATE additive_knowledge SET safety_desc='化学性质稳定,人体几乎不吸收,常用于粉末防结块。JECFA认定ADI''无需规定''。', disease_contraindication='严重肾功能不全者大量摄入慎用' WHERE id=58;
UPDATE additive_knowledge SET safety_desc='从柑橘皮、苹果渣等提取的天然多糖,属水溶性膳食纤维。人体不消化吸收,直接经肠道排出,JECFA认定ADI''无需规定'',安全性极高。过量摄入可能引起腹胀。', disease_contraindication='无明显禁忌人群,胃肠功能弱者大量摄入易腹胀' WHERE id=59;
UPDATE additive_knowledge SET safety_desc='海藻酸经丙二醇酯化的衍生物,在肠道部分水解释放海藻酸和丙二醇。JECFA设ADI为0-70 mg/kg体重(以海藻酸计)。', disease_contraindication='婴幼儿、孕妇大量摄入慎用' WHERE id=60;
UPDATE additive_knowledge SET safety_desc='海藻酸的钙盐,水溶性膳食纤维,人体不消化吸收。JECFA认定ADI''无需规定''。', disease_contraindication='高钙血症者大量摄入慎用' WHERE id=61;
UPDATE additive_knowledge SET safety_desc='海藻酸的钾盐,水溶性膳食纤维。JECFA认定ADI''无需规定'',安全性高。', disease_contraindication='高钾血症、严重肾功能不全者慎用' WHERE id=62;
UPDATE additive_knowledge SET safety_desc='褐藻提取的水溶性膳食纤维钠盐,人体不消化吸收。JECFA认定ADI''无需规定'',可在肠道吸附部分重金属和胆固醇。', disease_contraindication='高血压、限钠饮食者大量摄入慎用' WHERE id=63;
UPDATE additive_knowledge SET safety_desc='即维生素B2,人体必需营养素,水溶性,过量经尿排出。JECFA认定ADI''无需规定'',过量摄入可见尿液变黄(无害)。', disease_contraindication='无明显禁忌人群' WHERE id=64;
UPDATE additive_knowledge SET safety_desc='黑豆种皮提取的花色苷类天然色素,具一定抗氧化活性。', disease_contraindication='无明显禁忌人群' WHERE id=65;
UPDATE additive_knowledge SET safety_desc='黑加仑果实提取的花色苷类天然色素,合规用量下风险低。', disease_contraindication='无明显禁忌人群' WHERE id=66;
UPDATE additive_knowledge SET safety_desc='红花花瓣提取的天然黄色素,主要成分为查耳酮类化合物,常规用量下安全。', disease_contraindication='孕妇大量摄入慎用(红花本身有活血功效)' WHERE id=67;
UPDATE additive_knowledge SET safety_desc='红米米糠提取的天然色素,属花色苷类,安全性较高。', disease_contraindication='无明显禁忌人群' WHERE id=68;
UPDATE additive_knowledge SET safety_desc='红曲霉发酵提取的天然黄色素,常用于肉制品、糕点着色。JECFA未设ADI,安全性较高。工业产品可能伴生微量桔霉素(Citrinin),存在潜在肾毒性争议,应选择符合GB标准的产品。', disease_contraindication='肾功能不全者慎用' WHERE id=69;
UPDATE additive_knowledge SET safety_desc='红曲霉发酵大米得到的天然色素,常用于腐乳、肉制品着色。工业产品可能含微量桔霉素(Citrinin),存在肾毒性争议;同时可能含天然莫纳可林K,与他汀类降脂药存在相互作用风险。', disease_contraindication='肝肾功能不全、服用他汀类降脂药者慎用' WHERE id=70;
UPDATE additive_knowledge SET safety_desc='由琥珀酸、甘油和脂肪酸酯化得到,在消化道水解为甘油、脂肪酸和琥珀酸,均为人体内源代谢物。JECFA认为常规用量安全。', disease_contraindication='无明显禁忌人群' WHERE id=72;
UPDATE additive_knowledge SET safety_desc='提供贝类风味的有机酸钠盐,在体内进入三羧酸循环代谢。JECFA认定ADI''无需规定'',含钠量较高。', disease_contraindication='高血压、限钠饮食者慎用' WHERE id=73;
UPDATE additive_knowledge SET safety_desc='花生种皮提取的天然色素,属原花青素类,安全性较高。', disease_contraindication='花生过敏者慎用' WHERE id=74;
UPDATE additive_knowledge SET safety_desc='角豆树种子胚乳提取的半乳甘露聚糖,水溶性膳食纤维。JECFA认定ADI''无需规定''。', disease_contraindication='婴儿配方食品中需关注耐受性' WHERE id=75;
UPDATE additive_knowledge SET safety_desc='二元羧酸,在体内代谢效率较低,大部分以原形随尿排出。JECFA设ADI为0-5 mg/kg体重。', disease_contraindication='慢性肾功能不全者大量摄入慎用' WHERE id=82;
UPDATE additive_knowledge SET safety_desc='纤维素的甲醚化变性物,水溶性膳食纤维,人体不消化吸收。JECFA认定ADI''无需规定''。', disease_contraindication='肠梗阻者慎用' WHERE id=84;
UPDATE additive_knowledge SET safety_desc='来源于虾蟹甲壳的多糖,人体几乎不消化吸收,可吸附部分胆固醇和脂肪。', disease_contraindication='甲壳类海鲜过敏者禁用' WHERE id=85;
UPDATE additive_knowledge SET safety_desc='姜黄根茎研磨制品,含姜黄素和姜黄油。JECFA设姜黄素ADI为0-3 mg/kg体重,具抗氧化抗炎活性,大量摄入可能与抗凝药、化疗药相互作用。', disease_contraindication='胆结石、胆管阻塞、服用抗凝药者慎用,孕妇大量摄入慎用' WHERE id=86;
UPDATE additive_knowledge SET safety_desc='姜黄中的活性多酚成分,具强抗氧化和抗炎活性,水溶性差,口服生物利用度低。JECFA设ADI为0-3 mg/kg体重,可能影响铁吸收和抗凝药代谢。', disease_contraindication='胆结石、胆管阻塞、缺铁性贫血、服用抗凝药者慎用' WHERE id=87;
UPDATE additive_knowledge SET safety_desc='第Ⅲ类焦糖色,加氨工艺生产。JECFA设ADI为0-200 mg/kg体重。生产副产物4-甲基咪唑曾被IARC列为2B类(可能致癌物),需严控残留水平。', disease_contraindication='婴幼儿、孕妇大量摄入慎用' WHERE id=88;
UPDATE additive_knowledge SET safety_desc='第Ⅱ类焦糖色,仅限用于酒类。JECFA设ADI为0-160 mg/kg体重,含微量亚硫酸盐残留,亚硫酸盐敏感人群需慎用。', disease_contraindication='哮喘、亚硫酸盐过敏者慎用' WHERE id=89;
UPDATE additive_knowledge SET safety_desc='第Ⅰ类焦糖色,不使用氨或亚硫酸盐工艺,工艺最为温和。JECFA认定ADI''无需规定'',安全性最高。', disease_contraindication='无明显禁忌人群' WHERE id=90;
UPDATE additive_knowledge SET safety_desc='第Ⅳ类焦糖色,广泛用于可乐型饮料。JECFA设ADI为0-200 mg/kg体重。含4-甲基咪唑残留,需符合GB 2760限量。', disease_contraindication='婴幼儿、孕妇大量摄入慎用' WHERE id=91;
UPDATE additive_knowledge SET safety_desc='微生物发酵产生的水溶性多糖,人体不消化吸收。JECFA认定ADI''无需规定'',安全性高。', disease_contraindication='无明显禁忌人群' WHERE id=92;
UPDATE additive_knowledge SET safety_desc='金樱子果实提取的天然色素,合规剂量内安全。', disease_contraindication='无明显禁忌人群' WHERE id=93;
UPDATE additive_knowledge SET safety_desc='葡萄酿酒副产物,与碳酸氢钠配合作复合膨松剂。JECFA认定ADI''无需规定''。', disease_contraindication='高钾血症、严重肾功能不全者慎用' WHERE id=95;
UPDATE additive_knowledge SET safety_desc='仅限用于盐及代盐制品作抗结剂,使用量极低。常规摄入下安全。', disease_contraindication='血色素沉着症患者慎用' WHERE id=96;
UPDATE additive_knowledge SET safety_desc='菊花提取的天然黄色素,主要成分为黄酮类化合物,常规用量下安全。', disease_contraindication='无明显禁忌人群,菊科过敏者慎用' WHERE id=97;
UPDATE additive_knowledge SET safety_desc='高分子合成聚合物,人体不消化吸收。JECFA设ADI暂定值,GB 2760对使用范围有严格限制。', disease_contraindication='无明显禁忌人群' WHERE id=98;
UPDATE additive_knowledge SET safety_desc='即食用级硅油,化学性质极稳定,人体几乎不吸收。JECFA设ADI为0-1.5 mg/kg体重。', disease_contraindication='无明显禁忌人群' WHERE id=99;
UPDATE additive_knowledge SET safety_desc='用于巧克力降低粘度的特殊乳化剂,在体内水解为甘油和蓖麻油酸,经正常脂肪代谢途径处理。JECFA设ADI为0-25 mg/kg体重。', disease_contraindication='无明显禁忌人群' WHERE id=100;
UPDATE additive_knowledge SET safety_desc='由聚甘油与食用脂肪酸酯化得到,可被消化道脂肪酶水解为聚甘油和脂肪酸。JECFA设ADI为0-25 mg/kg体重。', disease_contraindication='无明显禁忌人群' WHERE id=101;
UPDATE additive_knowledge SET safety_desc='葡萄糖经聚合得到的水溶性膳食纤维,人体几乎不消化吸收,血糖反应低。JECFA认定ADI''无需规定'',过量可能引起腹胀腹泻。', disease_contraindication='肠易激综合征者大量摄入易腹泻' WHERE id=104;
UPDATE additive_knowledge SET safety_desc='仅限用于葡萄酒中防止酒石结晶,使用量极低。属氨基酸聚合物,可被部分降解为天冬氨酸。JECFA设ADI暂定值。', disease_contraindication='无明显禁忌人群' WHERE id=105;
UPDATE additive_knowledge SET safety_desc='仅限用于糖果包衣,化学性质稳定,人体几乎不吸收。JECFA设ADI为0-10 mg/kg体重。', disease_contraindication='无明显禁忌人群' WHERE id=107;
UPDATE additive_knowledge SET safety_desc='仅限用于糖果包衣,人体几乎不吸收,大部分原形排出。JECFA设ADI为0-50 mg/kg体重。', disease_contraindication='无明显禁忌人群' WHERE id=108;
UPDATE additive_knowledge SET safety_desc='决明子胚乳提取的半乳甘露聚糖,水溶性膳食纤维。JECFA设ADI暂定值。', disease_contraindication='慢性腹泻者慎用' WHERE id=109;
UPDATE additive_knowledge SET safety_desc='中枢神经兴奋剂,广泛存在于茶、咖啡中。GB 2760仅允许在可乐型碳酸饮料中限量使用,过量可引起心悸、失眠、胃肠不适。', disease_contraindication='心律失常、高血压、失眠、孕妇、儿童、消化性溃疡者慎用' WHERE id=110;
UPDATE additive_knowledge SET safety_desc='即维生素C,人体必需水溶性维生素,过量经尿排出。JECFA认定ADI''无需规定'',极大剂量(>2 g/日)可能引起腹泻或增加肾结石风险。', disease_contraindication='草酸盐性肾结石、葡萄糖-6-磷酸脱氢酶缺乏者大量补充慎用' WHERE id=112;
UPDATE additive_knowledge SET safety_desc='维生素C的钙盐形式,代谢途径相同。JECFA认定ADI''无需规定''。', disease_contraindication='高钙血症者大量摄入慎用' WHERE id=113;
UPDATE additive_knowledge SET safety_desc='维生素C的钠盐形式,水溶性更佳,代谢途径与维生素C相同。JECFA认定ADI''无需规定''。', disease_contraindication='高血压、限钠饮食者慎用' WHERE id=114;
UPDATE additive_knowledge SET safety_desc='维生素C的脂溶性衍生物,用于油脂抗氧化。在体内水解为维生素C和棕榈酸,JECFA设ADI为0-1.25 mg/kg体重。', disease_contraindication='无明显禁忌人群' WHERE id=115;
UPDATE additive_knowledge SET safety_desc='与化学合成的抗坏血酸棕榈酸酯化学结构相同,采用酶法生产工艺更绿色,安全性评价相同。', disease_contraindication='无明显禁忌人群' WHERE id=116;
UPDATE additive_knowledge SET safety_desc='微生物发酵产生的β-1,3-葡聚糖,水溶性膳食纤维,加热可形成热不可逆凝胶。JECFA认定ADI''无需规定''。', disease_contraindication='无明显禁忌人群' WHERE id=117;
UPDATE additive_knowledge SET safety_desc='可可豆壳提取的天然棕色素,合规用量下风险低。', disease_contraindication='无明显禁忌人群' WHERE id=118;
UPDATE additive_knowledge SET safety_desc='大豆水溶性膳食纤维,人体不消化吸收。JECFA认定ADI''无需规定''。', disease_contraindication='大豆严重过敏者慎用' WHERE id=119;
UPDATE additive_knowledge SET safety_desc='合成黄色素,JECFA设ADI为0-5 mg/kg体重。属''南安普顿6色素''之一,英国曾建议儿童食品避免使用,GB 2760限定仅可用于配制酒和糖果包衣。', disease_contraindication='儿童多动症、过敏体质者慎用' WHERE id=120;
UPDATE additive_knowledge SET safety_desc='辣椒果实提取的天然类胡萝卜素橙色素,安全性较高。', disease_contraindication='无明显禁忌人群' WHERE id=121;
UPDATE additive_knowledge SET safety_desc='红辣椒提取的天然类胡萝卜素红色素,主要成分为辣椒红素。JECFA设ADI暂定值,具抗氧化活性。', disease_contraindication='无明显禁忌人群' WHERE id=122;
UPDATE additive_knowledge SET safety_desc='辣椒提取物,含色素和辣椒素,具一定刺激性。常规用量下安全,过量可能刺激消化道。', disease_contraindication='胃溃疡、消化道炎症、痔疮患者慎用' WHERE id=123;
UPDATE additive_knowledge SET safety_desc='蓝靛果(忍冬科)果实提取的花色苷类天然色素,安全性较高。', disease_contraindication='无明显禁忌人群' WHERE id=124;
UPDATE additive_knowledge SET safety_desc='牛乳酪蛋白的钠盐,可作乳化剂和蛋白补充。可被人体正常消化吸收,安全性高。', disease_contraindication='牛奶蛋白过敏、苯丙酮尿症者慎用' WHERE id=125;
UPDATE additive_knowledge SET safety_desc='仅限作鲜水果表面防腐处理,使用量低。在体内可代谢为羟基化产物随尿排出。', disease_contraindication='食用前应清洗水果表面;肝肾功能不全者大量摄入慎用' WHERE id=126;
UPDATE additive_knowledge SET safety_desc='合成蓝色素,JECFA设ADI为0-12.5 mg/kg体重。摄入后大部分以原形随粪便排出,属''南安普顿6色素''之一。', disease_contraindication='儿童多动症、过敏体质者慎用' WHERE id=127;
UPDATE additive_knowledge SET safety_desc='经磷酸交联的变性淀粉,改善冻融稳定性。在肠道部分水解为葡萄糖和微量磷酸。JECFA认定ADI''无需规定''。', disease_contraindication='严重肾功能不全者慎用' WHERE id=130;
UPDATE additive_knowledge SET safety_desc='与磷酸化二淀粉磷酸酯类似,均为磷酸交联变性淀粉,代谢途径相同。JECFA认定ADI''无需规定''。', disease_contraindication='严重肾功能不全者慎用' WHERE id=131;
UPDATE additive_knowledge SET safety_desc='大豆或卵黄提取的天然乳化剂,主要成分为磷脂酰胆碱等,可被正常消化吸收。JECFA认定ADI''无需规定''。', disease_contraindication='大豆/蛋类过敏者慎用' WHERE id=132;
UPDATE additive_knowledge SET safety_desc='用于油脂和坚果包装的合成抗氧化剂,使用量低。JECFA设ADI为0-3 mg/kg体重。', disease_contraindication='婴幼儿大量摄入慎用' WHERE id=133;
UPDATE additive_knowledge SET safety_desc='元素硫,在燃烧或与水反应时产生二氧化硫起漂白防腐作用。残留以亚硫酸盐形式存在,代谢途径与二氧化硫相同。', disease_contraindication='哮喘、亚硫酸盐过敏、肝肾功能不全者慎用' WHERE id=134;
UPDATE additive_knowledge SET safety_desc='即食品级石膏,常用于豆腐凝固。在胃酸中部分溶解释放钙离子,溶解度低,人体吸收有限。JECFA认定ADI''无需规定''。', disease_contraindication='高钙血症、肾结石者大量摄入慎用' WHERE id=135;
UPDATE additive_knowledge SET safety_desc='含铝膨松剂,用于油条、粉丝等。铝在体内可在脑、骨骼蓄积,长期摄入与神经毒性、骨质疏松相关。JECFA将铝ADI修订为0-2 mg/kg体重(以铝计),儿童食品已限制使用。', disease_contraindication='阿尔茨海默病、慢性肾功能不全、孕妇、婴幼儿、儿童慎用' WHERE id=136;
UPDATE additive_knowledge SET safety_desc='仅限用于其他类饮用水补充镁元素,常规剂量下安全,过量摄入有泻下作用。', disease_contraindication='严重肾功能不全、心律失常者慎用' WHERE id=137;
UPDATE additive_knowledge SET safety_desc='仅限用于饮用水补充锌元素。锌为人体必需微量元素,过量可干扰铜吸收。', disease_contraindication='急性胃肠炎期间、肝豆状核变性者慎用' WHERE id=138;
UPDATE additive_knowledge SET safety_desc='用于腐乳类等强化铁元素,常用补铁补充剂,过量可引起胃肠刺激、便秘。', disease_contraindication='血色素沉着症、地中海贫血、消化性溃疡者慎用' WHERE id=139;
UPDATE additive_knowledge SET safety_desc='罗汉果提取的天然甜味剂,主要成分为罗汉果苷,甜度约为蔗糖300倍,几乎不被人体吸收,血糖反应低。', disease_contraindication='无明显禁忌人群' WHERE id=140;
UPDATE additive_knowledge SET safety_desc='罗望子种子提取的多糖,水溶性膳食纤维。JECFA认定ADI''无需规定''。', disease_contraindication='无明显禁忌人群' WHERE id=141;
UPDATE additive_knowledge SET safety_desc='红心萝卜提取的花色苷类天然色素,安全性较高。', disease_contraindication='无明显禁忌人群' WHERE id=142;
UPDATE additive_knowledge SET safety_desc='食品级钙盐,常用于豆制品凝固和水果罐头硬化处理。JECFA认定ADI''无需规定''。', disease_contraindication='高钙血症、肾结石者大量摄入慎用' WHERE id=143;
UPDATE additive_knowledge SET safety_desc='低钠盐主要成分,可替代部分氯化钠,过量可引起高钾血症。', disease_contraindication='高钾血症、肾功能不全、服用保钾利尿剂者慎用' WHERE id=144;
UPDATE additive_knowledge SET safety_desc='即卤水主要成分,常用于豆腐凝固。JECFA认定ADI''无需规定'',过量摄入有泻下作用。', disease_contraindication='严重肾功能不全、心律失常者慎用' WHERE id=145;
UPDATE additive_knowledge SET safety_desc='仅限用于鲜水果表面被膜,使用量低。', disease_contraindication='食用前应清洗水果表面' WHERE id=146;
UPDATE additive_knowledge SET safety_desc='多元醇甜味剂,血糖反应低,不易致龋齿。在小肠部分吸收,过量可引起渗透性腹泻。JECFA认定ADI''无需规定''。', disease_contraindication='肠易激综合征者大量摄入易腹泻' WHERE id=147;
UPDATE additive_knowledge SET safety_desc='合成酚类抗氧化剂,用于油脂和坚果防氧化。JECFA设ADI为0-1.4 mg/kg体重,极少数敏感人群可能皮肤过敏。', disease_contraindication='葡萄糖-6-磷酸脱氢酶缺乏、过敏体质者慎用' WHERE id=148;
UPDATE additive_knowledge SET safety_desc='玫瑰茄(洛神花)花萼提取的花色苷类天然色素,安全性较高。', disease_contraindication='孕妇大量摄入慎用' WHERE id=149;
UPDATE additive_knowledge SET safety_desc='大豆磷脂经磷脂酶水解得到,亲水性更佳,代谢途径与磷脂相同。', disease_contraindication='大豆过敏者慎用' WHERE id=150;
UPDATE additive_knowledge SET safety_desc='迷迭香叶提取的天然酚二萜类抗氧化剂。JECFA设ADI为0-0.3 mg/kg体重(以鼠尾草酸计)。', disease_contraindication='孕妇、癫痫患者大量摄入慎用' WHERE id=151;
UPDATE additive_knowledge SET safety_desc='动物结缔组织水解得到的蛋白质,可被人体正常消化吸收,安全性高。', disease_contraindication='极少数对动物胶原蛋白过敏者慎用' WHERE id=152;
UPDATE additive_knowledge SET safety_desc='仅限用于糖果包衣,使用量低。在消化道几乎不被吸收,JECFA设ADI为0-25 mg/kg体重。', disease_contraindication='无明显禁忌人群' WHERE id=153;
UPDATE additive_knowledge SET safety_desc='五碳糖醇,血糖反应低,不易致龋齿。在小肠部分吸收,过量可引起渗透性腹泻。JECFA认定ADI''无需规定''。注意:对犬类有严重低血糖毒性,需远离宠物。', disease_contraindication='肠易激综合征者大量摄入易腹泻' WHERE id=154;
UPDATE additive_knowledge SET safety_desc='木糖醇酐与硬脂酸酯化产物,在体内水解后通过正常代谢途径处理,常规用量下安全。', disease_contraindication='无明显禁忌人群' WHERE id=155;
UPDATE additive_knowledge SET safety_desc='多烯类抗真菌生物防腐剂,主要用于干酪和肉制品表面防霉。在消化道几乎不吸收,JECFA设ADI为0-0.3 mg/kg体重。', disease_contraindication='无明显禁忌人群' WHERE id=156;
UPDATE additive_knowledge SET safety_desc='广泛存在于柑橘类水果中,是人体三羧酸循环的中间产物,可被完全代谢为二氧化碳和水。JECFA认定ADI''无需规定'',合规剂量下安全。长期大量摄入可能腐蚀牙釉质或刺激胃黏膜。', disease_contraindication='胃溃疡、胃酸过多、龋齿患者慎用' WHERE id=159;
UPDATE additive_knowledge SET safety_desc='柠檬酸的钾盐,代谢途径与柠檬酸相同。JECFA认定ADI''无需规定''。', disease_contraindication='高钾血症、严重肾功能不全者慎用' WHERE id=160;
UPDATE additive_knowledge SET safety_desc='柠檬酸的钠盐,常用作酸度调节剂和螯合剂。JECFA认定ADI''无需规定'',含钠量较高。', disease_contraindication='高血压、限钠饮食者慎用' WHERE id=161;
UPDATE additive_knowledge SET safety_desc='仅限用于盐及代盐制品,使用量极低,可补充铁元素。', disease_contraindication='血色素沉着症患者慎用' WHERE id=162;
UPDATE additive_knowledge SET safety_desc='仅限用于罐头护色,使用量低。锡可在长期大量摄入下蓄积,GB 2760对锡限量有严格规定。', disease_contraindication='婴幼儿、孕妇大量摄入慎用' WHERE id=163;
UPDATE additive_knowledge SET safety_desc='柠檬酸的单钠盐,代谢途径与柠檬酸相同。JECFA认定ADI''无需规定''。', disease_contraindication='高血压、限钠饮食者慎用' WHERE id=164;
UPDATE additive_knowledge SET safety_desc='由柠檬酸、甘油和脂肪酸三者酯化得到,在消化道水解为柠檬酸、甘油和脂肪酸,均经正常代谢。JECFA认定ADI''无需规定''。', disease_contraindication='无明显禁忌人群' WHERE id=165;
UPDATE additive_knowledge SET safety_desc='阿斯巴甜衍生物,甜度约为蔗糖7000-13000倍,在低剂量下即可达到甜度需求,代谢生成的苯丙氨酸量极低。JECFA设ADI为0-2 mg/kg体重。', disease_contraindication='苯丙酮尿症患者大量摄入慎用' WHERE id=36;
UPDATE additive_knowledge SET safety_desc='酒石酸的脱水聚合物,仅限用于水果罐头。在水中可水解为酒石酸,代谢途径相同。', disease_contraindication='胃溃疡者慎用' WHERE id=170;
UPDATE additive_knowledge SET safety_desc='葡萄皮提取的花色苷类天然色素。JECFA设ADI暂定值,安全性较高。', disease_contraindication='无明显禁忌人群' WHERE id=171;
UPDATE additive_knowledge SET safety_desc='在水溶液中缓慢水解为葡萄糖酸,常用于内酯豆腐凝固。可被正常代谢,JECFA认定ADI''无需规定''。', disease_contraindication='无明显禁忌人群' WHERE id=172;
UPDATE additive_knowledge SET safety_desc='葡萄糖酸的钠盐,可被正常代谢。JECFA认定ADI''无需规定''。', disease_contraindication='高血压、限钠饮食者慎用' WHERE id=173;
UPDATE additive_knowledge SET safety_desc='用于腌渍蔬菜(如黑橄榄)护色,补充铁元素,常规用量下安全。', disease_contraindication='血色素沉着症、消化性溃疡者慎用' WHERE id=174;
UPDATE additive_knowledge SET safety_desc='出芽短梗霉发酵产生的水溶性多糖,人体几乎不消化吸收。JECFA认定ADI''无需规定''。', disease_contraindication='无明显禁忌人群' WHERE id=175;
UPDATE additive_knowledge SET safety_desc='经羟丙基化的变性淀粉,在肠道部分水解为葡萄糖。JECFA认定ADI''无需规定''。', disease_contraindication='无明显禁忌人群' WHERE id=176;
UPDATE additive_knowledge SET safety_desc='经羟丙基化和磷酸交联的变性淀粉,改善冻融稳定性,代谢途径与变性淀粉一致。JECFA认定ADI''无需规定''。', disease_contraindication='严重肾功能不全者慎用' WHERE id=177;
UPDATE additive_knowledge SET safety_desc='纤维素的羟丙基甲基醚,水溶性膳食纤维,人体不消化吸收。JECFA认定ADI''无需规定''。', disease_contraindication='肠梗阻者慎用' WHERE id=178;
UPDATE additive_knowledge SET safety_desc='油脂氧化产物,仅限用于油脂作晶种抑制剂。使用量低,JECFA设ADI暂定值。', disease_contraindication='婴幼儿大量摄入慎用' WHERE id=179;
UPDATE additive_knowledge SET safety_desc='松香经氢化和甘油酯化得到,在饮料中作密度调节剂。在消化道几乎不被吸收,JECFA设ADI为0-25 mg/kg体重。', disease_contraindication='无明显禁忌人群' WHERE id=180;
UPDATE additive_knowledge SET safety_desc='即熟石灰,与酸反应形成钙盐,可补充钙元素。JECFA认定ADI''无需规定''。', disease_contraindication='高钙血症、肾结石者大量摄入慎用' WHERE id=181;
UPDATE additive_knowledge SET safety_desc='强碱,与食品中酸反应形成钾盐,本身不残留。JECFA认定ADI''无需规定''。', disease_contraindication='高钾血症、严重肾功能不全者慎用' WHERE id=182;
UPDATE additive_knowledge SET safety_desc='红藻提取的水溶性膳食纤维,人体不消化吸收。JECFA认定ADI''无需规定'',安全性极高。', disease_contraindication='无明显禁忌人群' WHERE id=183;
UPDATE additive_knowledge SET safety_desc='蛋清提取的天然抗菌酶,可水解革兰阳性菌细胞壁。在消化道被蛋白酶降解为氨基酸。', disease_contraindication='鸡蛋蛋白过敏者慎用' WHERE id=185;
UPDATE additive_knowledge SET safety_desc='肉桂精油主要成分,具广谱抑菌活性,仅限用于鲜水果表面处理。常规残留水平下安全。', disease_contraindication='食用前应清洗水果表面,过敏体质者慎用' WHERE id=186;
UPDATE additive_knowledge SET safety_desc='人体糖酵解中间产物,可被完全代谢。JECFA认定ADI''无需规定'',婴幼儿对D-乳酸代谢能力较弱。', disease_contraindication='婴幼儿配方食品需关注异构体类型' WHERE id=187;
UPDATE additive_knowledge SET safety_desc='乳酸的钙盐,补钙效率较高。JECFA认定ADI''无需规定''。', disease_contraindication='高钙血症、肾结石者大量摄入慎用' WHERE id=188;
UPDATE additive_knowledge SET safety_desc='乳酸的钾盐,代谢途径与乳酸相同。JECFA认定ADI''无需规定''。', disease_contraindication='高钾血症、严重肾功能不全者慎用' WHERE id=189;
UPDATE additive_knowledge SET safety_desc='乳酸的钠盐,代谢途径与乳酸相同。JECFA认定ADI''无需规定'',含钠量较高。', disease_contraindication='高血压、限钠饮食者慎用' WHERE id=191;
UPDATE additive_knowledge SET safety_desc='由乳酸、甘油和脂肪酸酯化得到,在消化道水解为各组分,经正常代谢。JECFA认定ADI''无需规定''。', disease_contraindication='无明显禁忌人群' WHERE id=192;
UPDATE additive_knowledge SET safety_desc='多元醇甜味剂,人体几乎不吸收,在结肠被微生物发酵。JECFA认定ADI''无需规定'',过量可引起渗透性腹泻。', disease_contraindication='肠易激综合征者大量摄入易腹泻' WHERE id=193;
UPDATE additive_knowledge SET safety_desc='用于水解乳制品中乳糖,生成葡萄糖和半乳糖。在加工或消化中失活,本身被消化为氨基酸,安全性高。', disease_contraindication='半乳糖血症者慎用经乳糖酶处理的乳制品' WHERE id=194;
UPDATE additive_knowledge SET safety_desc='微生物发酵产生的多糖,水溶性膳食纤维,常规用量下安全。', disease_contraindication='无明显禁忌人群' WHERE id=196;
UPDATE additive_knowledge SET safety_desc='桑椹果实提取的花色苷类天然色素,安全性较高。', disease_contraindication='无明显禁忌人群' WHERE id=197;
UPDATE additive_knowledge SET safety_desc='沙蒿种子提取的多糖,水溶性膳食纤维,常规用量下安全。', disease_contraindication='无明显禁忌人群' WHERE id=198;
UPDATE additive_knowledge SET safety_desc='沙棘果实提取的天然类胡萝卜素黄色素,安全性较高。', disease_contraindication='无明显禁忌人群' WHERE id=199;
UPDATE additive_knowledge SET safety_desc='多元醇甜味剂,水果中天然存在,血糖反应低。在小肠缓慢吸收,过量可引起渗透性腹泻和腹胀。JECFA认定ADI''无需规定''。', disease_contraindication='肠易激综合征、果糖不耐受者慎用' WHERE id=202;
UPDATE additive_knowledge SET safety_desc='醋酸和醋酸钠的复合物,常用于面包防霉。代谢途径与醋酸相同,JECFA设ADI为0-15 mg/kg体重。', disease_contraindication='高血压、限钠饮食者慎用' WHERE id=203;
UPDATE additive_knowledge SET safety_desc='多组分甘油酯类乳化剂,在消化道水解为甘油、脂肪酸、酒石酸和乙酸,均经正常代谢。JECFA设ADI为0-50 mg/kg体重。', disease_contraindication='无明显禁忌人群' WHERE id=204;
UPDATE additive_knowledge SET safety_desc='由山梨糖醇酐与脂肪酸酯化得到,常与吐温配合使用。在消化道水解为山梨糖醇酐和脂肪酸,JECFA设ADI为0-25 mg/kg体重。', disease_contraindication='无明显禁忌人群' WHERE id=200;
UPDATE additive_knowledge SET safety_desc='仅限用于鲜水果蔬菜表面被膜,使用量低。', disease_contraindication='食用前应清洗果蔬表面' WHERE id=205;
UPDATE additive_knowledge SET safety_desc='经稀酸轻度水解的变性淀粉,代谢途径与天然淀粉相同。JECFA认定ADI''无需规定''。', disease_contraindication='无明显禁忌人群' WHERE id=206;
UPDATE additive_knowledge SET safety_desc='偶氮类合成红色素,JECFA设ADI为0-4 mg/kg体重。属''南安普顿6色素''之一,可能与儿童多动行为相关。', disease_contraindication='儿童多动症、过敏体质、哮喘者慎用' WHERE id=207;
UPDATE additive_knowledge SET safety_desc='经羧甲基化的变性淀粉,水溶性膳食纤维,常规用量下安全。', disease_contraindication='高血压、限钠饮食者慎用' WHERE id=208;
UPDATE additive_knowledge SET safety_desc='纤维素的羧甲基醚钠盐,水溶性膳食纤维,人体不消化吸收。JECFA认定ADI''无需规定'',近年研究提示可能影响肠道菌群。', disease_contraindication='肠易激综合征者大量摄入慎用' WHERE id=209;
UPDATE additive_knowledge SET safety_desc='西非神秘果提取的天然蛋白质甜味剂,甜度约为蔗糖2000-3000倍,在消化道被蛋白酶降解为氨基酸。JECFA认定ADI''无需规定''。', disease_contraindication='无明显禁忌人群' WHERE id=210;
UPDATE additive_knowledge SET safety_desc='受热分解为氨气、二氧化碳和水,本身在烘焙后残留极少,常规用量下安全。', disease_contraindication='严重肝功能不全者慎用(氨代谢)' WHERE id=211;
UPDATE additive_knowledge SET safety_desc='即天然石灰石/方解石主要成分,常用作钙强化剂。在胃酸中部分溶解释放钙离子。JECFA认定ADI''无需规定''。', disease_contraindication='高钙血症、肾结石、严重肾功能不全者大量摄入慎用' WHERE id=212;
UPDATE additive_knowledge SET safety_desc='强碱性钾盐,与酸反应形成相应钾盐。JECFA认定ADI''无需规定''。', disease_contraindication='高钾血症、严重肾功能不全者慎用' WHERE id=213;
UPDATE additive_knowledge SET safety_desc='碱性镁盐,常用作面粉处理剂和抗结剂。在胃酸中部分溶解释放镁离子。JECFA认定ADI''无需规定''。', disease_contraindication='严重肾功能不全、心律失常者慎用' WHERE id=214;
UPDATE additive_knowledge SET safety_desc='即纯碱,常用作面碱。在胃酸中迅速中和,本身不蓄积。JECFA认定ADI''无需规定''。', disease_contraindication='高血压、限钠饮食者慎用' WHERE id=215;
UPDATE additive_knowledge SET safety_desc='即臭粉,受热分解为氨气、二氧化碳和水,在烘焙中残留极少,常规用量下安全。', disease_contraindication='严重肝功能不全者慎用' WHERE id=216;
UPDATE additive_knowledge SET safety_desc='弱碱性钾盐,常用作酸度调节剂。JECFA认定ADI''无需规定''。', disease_contraindication='高钾血症、严重肾功能不全者慎用' WHERE id=217;
UPDATE additive_knowledge SET safety_desc='碳酸钠和碳酸氢钠的复合盐,代谢途径相同。JECFA认定ADI''无需规定''。', disease_contraindication='高血压、限钠饮食者慎用' WHERE id=219;
UPDATE additive_knowledge SET safety_desc='阿斯巴甜与安赛蜜的盐复合物,在体内解离后分别代谢。代谢产生苯丙氨酸,苯丙酮尿症患者禁用,JECFA单独评估其ADI。', disease_contraindication='苯丙酮尿症、孕妇、儿童慎用' WHERE id=224;
UPDATE additive_knowledge SET safety_desc='从棕榈油、胡萝卜或藻类提取的天然β-胡萝卜素及类胡萝卜素混合物。维生素A原,代谢可控,JECFA设ADI暂定值。', disease_contraindication='无明显禁忌人群' WHERE id=225;
UPDATE additive_knowledge SET safety_desc='苋菜植株提取的甜菜红素类天然色素(注意区别于合成苋菜红INS 123),安全性较高。', disease_contraindication='无明显禁忌人群' WHERE id=226;
UPDATE additive_knowledge SET safety_desc='田菁种子胚乳提取的半乳甘露聚糖,水溶性膳食纤维,常规用量下安全。', disease_contraindication='无明显禁忌人群' WHERE id=227;
UPDATE additive_knowledge SET safety_desc='红甜菜根提取的天然色素,主要成分为甜菜苷。可使尿液短暂呈红色(无害),JECFA认定ADI''无需规定''。', disease_contraindication='无明显禁忌人群' WHERE id=228;
UPDATE additive_knowledge SET safety_desc='甜叶菊提取的天然甜味剂,甜度约为蔗糖200-300倍,几乎不被吸收。JECFA设ADI为0-4 mg/kg体重(以甜菊醇计),血糖反应低。', disease_contraindication='低血压患者大量摄入慎用' WHERE id=229;
UPDATE additive_knowledge SET safety_desc='聚氧乙烯山梨醇酐脂肪酸酯,与司盘类配合使用。在消化道部分水解,JECFA设ADI为0-25 mg/kg体重。', disease_contraindication='无明显禁忌人群' WHERE id=106;
UPDATE additive_knowledge SET safety_desc='甲壳素脱乙酰化得到,可吸附脂肪和胆固醇,人体几乎不消化吸收。', disease_contraindication='甲壳类海鲜过敏者禁用' WHERE id=231;
UPDATE additive_knowledge SET safety_desc='经酸水解纤维素得到的不溶性膳食纤维,人体不消化吸收。JECFA认定ADI''无需规定''。', disease_contraindication='肠梗阻者慎用' WHERE id=232;
UPDATE additive_knowledge SET safety_desc='脂溶性维生素,兼作天然抗氧化剂。生理剂量内对人体有益,可保护细胞免受氧化损伤。作为补充剂长期超量(>400 IU/日)可能增加出血风险或干扰维生素K代谢,食品添加用量远低于此。', disease_contraindication='服用抗凝药者、维生素K缺乏者大量补充慎用' WHERE id=233;
UPDATE additive_knowledge SET safety_desc='用于水产品防腐消毒,在食品加工中分解,本身不残留,残留产物以氯化物为主。JECFA设ADI为0-0.03 mg/kg体重。', disease_contraindication='婴幼儿大量摄入慎用' WHERE id=234;
UPDATE additive_knowledge SET safety_desc='植物细胞壁主要成分,人体不消化吸收的膳食纤维。JECFA认定ADI''无需规定'',安全性极高。', disease_contraindication='肠梗阻、严重肠粘连者慎用' WHERE id=235;
UPDATE additive_knowledge SET safety_desc='偶氮类合成红色素,JECFA设ADI为0-0.5 mg/kg体重。摄入后大部分以原形随粪便排出,少部分由肠道菌还原为芳香胺类,可能与儿童多动行为相关。', disease_contraindication='儿童多动症、过敏体质、哮喘者慎用' WHERE id=236;
UPDATE additive_knowledge SET safety_desc='橡子壳提取的天然棕色素,主要成分为单宁类,常规用量下安全。', disease_contraindication='无明显禁忌人群' WHERE id=237;
UPDATE additive_knowledge SET safety_desc='中链甘油三酯衍生物,可被脂肪酶水解为甘油和中链脂肪酸,经β-氧化代谢供能,安全性高。', disease_contraindication='无明显禁忌人群' WHERE id=239;
UPDATE additive_knowledge SET safety_desc='经辛烯基琥珀酸酯化的变性淀粉,具乳化能力。在肠道部分水解,JECFA设ADI为0-25 mg/kg体重。', disease_contraindication='无明显禁忌人群' WHERE id=240;
UPDATE additive_knowledge SET safety_desc='偶氮类合成红色素,我国独立标识号。JECFA设ADI暂定值,GB 2760对使用范围有限制。', disease_contraindication='儿童多动症、过敏体质者慎用' WHERE id=241;
UPDATE additive_knowledge SET safety_desc='亚麻籽提取的水溶性膳食纤维,常规用量下安全。', disease_contraindication='无明显禁忌人群' WHERE id=242;
UPDATE additive_knowledge SET safety_desc='仅限用于盐及代盐制品作抗结剂,使用量极低(≤10 mg/kg)。氰离子与铁紧密结合不易释放,正常烹饪温度下稳定,JECFA设ADI为0-0.025 mg/kg体重。', disease_contraindication='严重肾功能不全者大量摄入慎用' WHERE id=243;
UPDATE additive_knowledge SET safety_desc='胭脂虫(雌性介壳虫)提取的天然红色素,主要成分为胭脂红酸。JECFA设ADI为0-5 mg/kg体重,极少数人可能出现过敏反应。', disease_contraindication='昆虫蛋白过敏、哮喘者慎用' WHERE id=245;
UPDATE additive_knowledge SET safety_desc='胭脂树种子提取的天然橙色素,主要成分为红木素。JECFA设ADI暂定值。', disease_contraindication='极少数过敏体质者慎用' WHERE id=247;
UPDATE additive_knowledge SET safety_desc='强酸,仅限用于蛋黄酱、沙拉酱中和pH。在食品中迅速被中和形成氯化物,本身不残留。', disease_contraindication='严重胃食管反流者慎用' WHERE id=248;
UPDATE additive_knowledge SET safety_desc='杨梅果实提取的花色苷类天然色素,安全性较高。', disease_contraindication='无明显禁忌人群' WHERE id=249;
UPDATE additive_knowledge SET safety_desc='经次氯酸钠等氧化剂处理的变性淀粉,残留氯极少,代谢途径与淀粉相似。JECFA认定ADI''无需规定''。', disease_contraindication='无明显禁忌人群' WHERE id=250;
UPDATE additive_knowledge SET safety_desc='经氧化和羟丙基化的双重变性淀粉,代谢途径与变性淀粉一致,常规用量下安全。', disease_contraindication='无明显禁忌人群' WHERE id=251;
UPDATE additive_knowledge SET safety_desc='无机铁氧化物色素,仅限用于糖果包衣,使用量极低,化学性质稳定,人体几乎不吸收。', disease_contraindication='血色素沉着症患者慎用' WHERE id=252;
UPDATE additive_knowledge SET safety_desc='万寿菊等植物提取的天然类胡萝卜素,无维生素A活性,可在视网膜黄斑区蓄积有益视力。JECFA设ADI为0-2 mg/kg体重。', disease_contraindication='无明显禁忌人群' WHERE id=253;
UPDATE additive_knowledge SET safety_desc='叶绿素经铜替代镁中心得到的脂溶性绿色素,JECFA设ADI为0-15 mg/kg体重。', disease_contraindication='肝豆状核变性、严重肝功能不全者慎用' WHERE id=254;
UPDATE additive_knowledge SET safety_desc='叶绿素铜的水溶性盐形式,代谢评价相同。JECFA设ADI为0-15 mg/kg体重。', disease_contraindication='肝豆状核变性者慎用' WHERE id=255;
UPDATE additive_knowledge SET safety_desc='与普通二氧化碳化学性质相同,生产工艺不同,安全性评价同二氧化碳。', disease_contraindication='严重胃食管反流者过量饮用碳酸饮料慎用' WHERE id=256;
UPDATE additive_knowledge SET safety_desc='强螯合剂,可结合金属离子防止氧化变色。JECFA设ADI为0-2.5 mg/kg体重,长期大量摄入可能影响微量元素吸收。', disease_contraindication='缺铁、缺锌、缺钙者大量摄入慎用' WHERE id=257;
UPDATE additive_knowledge SET safety_desc='EDTA的钙钠复合盐,可避免对钙的螯合掠夺,代谢评价类似EDTA二钠。JECFA设ADI为0-2.5 mg/kg体重。', disease_contraindication='缺铁、缺锌者大量摄入慎用' WHERE id=258;
UPDATE additive_knowledge SET safety_desc='醋酸的钠盐,代谢途径与醋酸相同。JECFA认定ADI''无需规定'',含钠量较高。', disease_contraindication='高血压、限钠饮食者慎用' WHERE id=259;
UPDATE additive_knowledge SET safety_desc='由乙酸、甘油和脂肪酸酯化得到,在消化道水解为各组分,经正常代谢。JECFA认定ADI''无需规定''。', disease_contraindication='无明显禁忌人群' WHERE id=260;
UPDATE additive_knowledge SET safety_desc='经乙酰化和磷酸交联的变性淀粉,改善冻融稳定性。JECFA认定ADI''无需规定''。', disease_contraindication='严重肾功能不全者慎用' WHERE id=261;
UPDATE additive_knowledge SET safety_desc='经乙酰化和己二酸交联的变性淀粉,代谢途径与变性淀粉一致。JECFA认定ADI''无需规定''。', disease_contraindication='无明显禁忌人群' WHERE id=262;
UPDATE additive_knowledge SET safety_desc='仅限用于鲜水果防腐处理(如苹果、梨),抗氧化抑制虎皮病。JECFA曾设ADI暂定值,部分国家因致癌性争议已收紧使用。', disease_contraindication='食用前应清洗水果表面,孕妇、婴幼儿、肝肾功能不全者慎用' WHERE id=264;
UPDATE additive_knowledge SET safety_desc='乳糖经异构化得到的低聚糖,血糖反应低,可促进肠道双歧杆菌增殖,安全性较高。', disease_contraindication='半乳糖血症者慎用' WHERE id=266;
UPDATE additive_knowledge SET safety_desc='蔗糖经酶法异构化得到的还原性二糖,血糖反应低于蔗糖,不易致龋齿,常规用量下安全。', disease_contraindication='蔗糖酶-异麦芽糖酶缺乏症者慎用' WHERE id=267;
UPDATE additive_knowledge SET safety_desc='长链饱和脂肪酸,广泛存在于动植物脂肪中,可经β-氧化代谢供能。JECFA认定ADI''无需规定''。', disease_contraindication='无明显禁忌人群' WHERE id=268;
UPDATE additive_knowledge SET safety_desc='硬脂酸的钙盐,在胃酸中可释放钙离子,常规用量下安全。', disease_contraindication='高钙血症者大量摄入慎用' WHERE id=269;
UPDATE additive_knowledge SET safety_desc='硬脂酸的钾盐,代谢途径与硬脂酸相同,常规用量下安全。', disease_contraindication='高钾血症、严重肾功能不全者慎用' WHERE id=270;
UPDATE additive_knowledge SET safety_desc='硬脂酸的镁盐,常用作粉末抗结剂,化学性质稳定,人体几乎不吸收。JECFA认定ADI''无需规定''。', disease_contraindication='严重肾功能不全者慎用' WHERE id=271;
UPDATE additive_knowledge SET safety_desc='由硬脂酸、乳酸和钠/钙形成的复合乳化剂,常用于面包改良。在消化道水解为各组分,正常代谢。JECFA设ADI为0-20 mg/kg体重。', disease_contraindication='钠盐型者高血压患者慎用' WHERE id=272;
UPDATE additive_knowledge SET safety_desc='玉米提取的类胡萝卜素天然黄色素,主要成分为玉米黄质和叶黄素,安全性较高。', disease_contraindication='无明显禁忌人群' WHERE id=274;
UPDATE additive_knowledge SET safety_desc='越橘果实提取的花色苷类天然色素,具一定抗氧化活性,安全性较高。', disease_contraindication='无明显禁忌人群' WHERE id=275;
UPDATE additive_knowledge SET safety_desc='螺旋藻提取的天然蓝色素,主要成分为藻蓝蛋白,可被消化吸收,安全性较高。', disease_contraindication='苯丙酮尿症者大量摄入慎用(蛋白质中含苯丙氨酸)' WHERE id=276;
UPDATE additive_knowledge SET safety_desc='皂荚种子提取的多糖,水溶性膳食纤维,常规用量下安全。', disease_contraindication='无明显禁忌人群' WHERE id=277;
UPDATE additive_knowledge SET safety_desc='智利皂皮树提取物,含皂苷类化合物,仅限低剂量用于饮料起泡和乳化。JECFA设ADI为0-5 mg/kg体重(以皂苷计)。', disease_contraindication='大量摄入可能引起消化道刺激,孕妇慎用' WHERE id=278;
UPDATE additive_knowledge SET safety_desc='蔗糖与脂肪酸酯化得到,在消化道水解为蔗糖和脂肪酸,经正常代谢。JECFA设ADI为0-30 mg/kg体重。', disease_contraindication='无明显禁忌人群' WHERE id=279;
UPDATE additive_knowledge SET safety_desc='栀子果实提取的天然黄色素,主要成分为藏花素,常规用量下安全。', disease_contraindication='孕妇大量摄入慎用' WHERE id=280;
UPDATE additive_knowledge SET safety_desc='栀子提取物经酶处理得到的蓝色素,安全性较高。', disease_contraindication='孕妇大量摄入慎用' WHERE id=281;
UPDATE additive_knowledge SET safety_desc='谷物麸皮天然成分,具螯合金属和抗氧化作用。属''抗营养因子'',可结合矿物质降低吸收。', disease_contraindication='缺铁、缺锌、缺钙、骨质疏松者大量摄入慎用' WHERE id=282;
UPDATE additive_knowledge SET safety_desc='椰子壳等植物经高温碳化得到的黑色素,化学性质稳定,人体几乎不吸收。JECFA认定ADI''无需规定''。', disease_contraindication='服药期间慎用(可能吸附药物影响吸收)' WHERE id=283;
UPDATE additive_knowledge SET safety_desc='竹叶提取物,主要成分为黄酮类多酚,具抗氧化活性,常规用量下安全。', disease_contraindication='无明显禁忌人群' WHERE id=284;
UPDATE additive_knowledge SET safety_desc='紫草根提取的天然色素,主要成分为紫草素,具抗炎活性,合规剂量下安全。', disease_contraindication='孕妇大量摄入慎用' WHERE id=285;
UPDATE additive_knowledge SET safety_desc='紫甘薯提取的花色苷类天然色素,具抗氧化活性,安全性较高。', disease_contraindication='无明显禁忌人群' WHERE id=286;
UPDATE additive_knowledge SET safety_desc='紫胶虫分泌物的精制产品,人体几乎不吸收,JECFA未设具体ADI,合规用量下安全。', disease_contraindication='昆虫蛋白过敏者慎用' WHERE id=287;
UPDATE additive_knowledge SET safety_desc='紫胶虫分泌物中提取的红色素,主要成分为紫胶酸,安全性较高。', disease_contraindication='昆虫蛋白过敏者慎用' WHERE id=288;
UPDATE additive_knowledge SET safety_desc='棕榈油等提取的生育三烯酚和生育酚混合物,具维生素E活性。生理剂量内对人体有益,大量摄入可能干扰维生素K代谢。', disease_contraindication='服用抗凝药、维生素K缺乏者大量摄入慎用' WHERE id=289;
UPDATE additive_knowledge SET safety_desc='橄榄油及橄榄叶中天然存在的多酚抗氧化剂,具强自由基清除活性。仅限用于植物油,使用量低,常规用量下安全。', disease_contraindication='无明显禁忌人群' WHERE id=290;

-- 共更新 266 条